INSTALL SONAME 'auth_pam';
/*INSTALL SONAME 'sha256_password';*/

/*CREATE USER "rw-user" IDENTIFIED VIA pam USING 'mariadb';*/
CREATE USER "rw-user" IDENTIFIED BY 'aldu';
GRANT SELECT,INSERT,UPDATE,DELETE ON booksdb.BOOKS TO "rw-user";
GRANT SELECT,INSERT,UPDATE,DELETE ON booksdb.BOOKS_SUBJECTS_ASSOC TO "rw-user";
GRANT SELECT,INSERT,UPDATE,DELETE ON booksdb.FILE_STORE TO "rw-user";
GRANT SELECT,INSERT,UPDATE,DELETE ON booksdb.BOOKS_LINKS TO "rw-user";
GRANT SELECT,INSERT,UPDATE,DELETE ON booksdb.IT_SUBJECT TO "rw-user";

/*CREATE USER "ro-user" IDENTIFIED VIA pam USING 'mariadb';*/
CREATE USER "ro-user" IDENTIFIED BY 'aldu';
GRANT SELECT ON booksdb.BOOKS_SUBJECTS_ASSOC TO "ro-user";
GRANT SELECT ON booksdb.BOOKS TO "ro-user";
GRANT SELECT ON booksdb.FILE_STORE TO "ro-user";
GRANT SELECT ON booksdb.BOOKS_LINKS TO "ro-user";
GRANT SELECT ON booksdb.IT_SUBJECT TO "ro-user";

